const DETAIL_MOVIE_REQUEST = '@detailmovie/DETAIL_MOVIE_REQUEST';
const DETAIL_MOVIE_SUCCESS = '@detailmovie/DETAIL_MOVIE_SUCCESS';
const DETAIL_MOVIE_FAILED = '@detailmovie/DETAIL_MOVIE_FAILED';

export { DETAIL_MOVIE_REQUEST, DETAIL_MOVIE_SUCCESS, DETAIL_MOVIE_FAILED }