const LIST_MOVIES_REQUEST = '@listmovies/LIST_MOVIES_REQUEST';
const LIST_MOVIES_SUCCESS = '@listmovies/LIST_MOVIES_SUCCESS';
const LIST_MOVIES_FAILED = '@listmovies/LIST_MOVIES_FAILED';

export { LIST_MOVIES_REQUEST, LIST_MOVIES_SUCCESS, LIST_MOVIES_FAILED }