const ADD_USER_REQUEST = "@add-user/ADD_USER_REQUEST";
const ADD_USER_SUCCESS = "@add-user/ADD_USER_SUCCESS";
const ADD_USER_FAILED = "@add-user/ADD_USER_REQUEST";

export { ADD_USER_REQUEST, ADD_USER_SUCCESS, ADD_USER_FAILED };